---
- name: Configurar NOPASSWD en sudoers
  hosts: all
  become: true
  become_method: sudo

  tasks:
    - name: Verificar sistema Debian/Ubuntu
      fail:
        msg: "Solo sistemas Debian"
      when: ansible_os_family != "Debian"

    - name: Configurar sudoers NOPASSWD para ultdrako
      ansible.builtin.copy:
        content: "ultdrako ALL=(ALL) NOPASSWD:ALL\n"
        dest: /etc/sudoers.d/ultdrako
        mode: '0440'
        owner: root
        group: root

    - name: Verificar usuario efectivo post-become
      ansible.builtin.command: whoami
      register: result
      changed_when: false

    - name: Resultado
      debug:
        msg: "{{ inventory_hostname }}: usuario = {{ result.stdout }}"
