# ============================================================================
# Drakos SOC - Inventario Windows completo
# Fecha: 2026-06-22
# 10 hosts Windows Server 2025
# ============================================================================

[windows_ultdrako]
DrakosTrooper  ansible_host=192.168.13.238
drakoshv       ansible_host=192.168.13.252
Veeam          ansible_host=192.168.13.250
Vesta          ansible_host=192.168.13.232
nicorobin      ansible_host=192.168.13.239
DrakosDHCP     ansible_host=192.168.13.251
DPS            ansible_host=192.168.13.245
Nami           ansible_host=192.168.13.231
BoaHancock     ansible_host=192.168.13.230

[windows_administrator]
Backups2       ansible_host=192.168.13.237

[windows:children]
windows_ultdrako
windows_administrator

[windows_ultdrako:vars]
ansible_connection=ssh
ansible_shell_type=powershell
ansible_user=ultdrako
ansible_ssh_private_key_file=/home/ultdrako/.ssh/ansible_windows
ansible_ssh_common_args='-o StrictHostKeyChecking=accept-new -o IdentitiesOnly=yes'

[windows_administrator:vars]
ansible_connection=ssh
ansible_shell_type=powershell
ansible_user=Administrator
ansible_ssh_private_key_file=/home/ultdrako/.ssh/ansible_windows
ansible_ssh_common_args='-o StrictHostKeyChecking=accept-new -o IdentitiesOnly=yes'
