---
- hosts: all
  become: yes
  become_method: sudo
  become_user: root
  
  tasks:
    - name: Verificar acceso sudo
      command: whoami
      register: user_check
      
    - name: Mostrar usuario actual
      debug:
        msg: "Ejecutándose como: {{ user_check.stdout }}"
        
    - name: Actualizar lista de paquetes
      shell: |
        export DEBIAN_FRONTEND=noninteractive
        apt-get update
      environment:
        DEBIAN_FRONTEND: noninteractive
      register: apt_update
      
    - name: Actualizar paquetes del sistema
      shell: |
        export DEBIAN_FRONTEND=noninteractive
        apt-get upgrade -y
      environment:
        DEBIAN_FRONTEND: noninteractive
      register: apt_upgrade
      
    - name: Limpiar paquetes huérfanos
      shell: |
        export DEBIAN_FRONTEND=noninteractive
        apt-get autoremove -y && apt-get autoclean
      environment:
        DEBIAN_FRONTEND: noninteractive
      register: apt_clean
      
    - name: Mostrar resumen de actualización
      debug:
        msg: |
          ✓ Update completado: {{ apt_update.rc == 0 }}
          ✓ Upgrade completado: {{ apt_upgrade.rc == 0 }}  
          ✓ Limpieza completada: {{ apt_clean.rc == 0 }}
