---
- hosts: all
  become: true
  become_method: sudo
  serial: 3
  tasks:
    - name: Verificar que el sistema es Debian/Ubuntu
      fail:
        msg: "Este playbook solo funciona en sistemas basados en Debian"
      when: ansible_os_family != "Debian"

    - name: Verificar privilegios de root
      command: whoami
      register: current_user
      changed_when: false

    - name: Mostrar usuario actual
      debug:
        msg: "Ejecutando como: {{ current_user.stdout }}"

    - name: Esperar a que se libere el lock de dpkg/apt
      shell: |
        timeout=60
        elapsed=0
        while [ $elapsed -lt $timeout ]; do
          if ! fuser /var/lib/dpkg/lock-frontend /var/lib/apt/lists/lock /var/cache/apt/archives/lock 2>/dev/null; then
            exit 0
          fi
          sleep 2
          elapsed=$((elapsed + 2))
        done
      become: true
      become_user: root
      changed_when: false
      failed_when: false

    - name: Matar procesos que bloquean APT (si existen)
      shell: |
        pkill -9 apt || true
        pkill -9 apt-get || true
        pkill -9 dpkg || true
        pkill -9 unattended-upgrade || true
      become: true
      become_user: root
      changed_when: false
      failed_when: false

    - name: Eliminar locks de APT si existen
      file:
        path: "{{ item }}"
        state: absent
      become: true
      become_user: root
      loop:
        - /var/lib/dpkg/lock
        - /var/lib/dpkg/lock-frontend
        - /var/lib/apt/lists/lock
        - /var/cache/apt/archives/lock
      failed_when: false

    - name: Reconfigurar dpkg si es necesario
      command: dpkg --configure -a
      become: true
      become_user: root
      register: dpkg_configure
      changed_when: false
      failed_when: false

    - name: Actualizar caché de APT
      apt:
        update_cache: yes
        cache_valid_time: 0
        force_apt_get: yes
      become: true
      become_user: root
      environment:
        DEBIAN_FRONTEND: noninteractive
      register: apt_cache_update
      retries: 3
      delay: 15
      until: apt_cache_update is success

    - name: Actualizar todos los paquetes a la última versión
      apt:
        upgrade: dist
        update_cache: no
        force_apt_get: yes
        autoremove: yes
        autoclean: yes
        dpkg_options: 'force-confdef,force-confold'
      become: true
      become_user: root
      environment:
        DEBIAN_FRONTEND: noninteractive
      register: apt_upgrade_result
      timeout: 1800

    - name: Mostrar resumen de actualizaciones
      debug:
        msg: 
          - "Host: {{ inventory_hostname }}"
          - "Estado: {{ 'Actualizado correctamente' if apt_upgrade_result.changed else 'Sin actualizaciones disponibles' }}"
      when: apt_upgrade_result is defined

    - name: Verificar si se requiere reinicio
      stat:
        path: /var/run/reboot-required
      register: reboot_required

    - name: Leer motivo del reinicio si existe
      slurp:
        src: /var/run/reboot-required.pkgs
      register: reboot_packages
      when: reboot_required.stat.exists
      failed_when: false

    - name: Notificar si se requiere reinicio
      debug:
        msg: 
          - "⚠️  {{ inventory_hostname }} REQUIERE REINICIO"
          - "Paquetes que requieren reinicio:"
          - "{{ (reboot_packages.content | b64decode).split('\n') | select() | list }}"
      when: 
        - reboot_required.stat.exists
        - reboot_packages is defined
        - reboot_packages.content is defined

    - name: Generar reporte final
      debug:
        msg:
          - "================================"
          - "Host: {{ inventory_hostname }}"
          - "IP: {{ ansible_default_ipv4.address | default('N/A') }}"
          - "Sistema: {{ ansible_distribution }} {{ ansible_distribution_version }}"
          - "Kernel: {{ ansible_kernel }}"
          - "Python: {{ ansible_python_version }}"
          - "Actualización: {{ 'COMPLETADA' if apt_upgrade_result.changed else 'SIN CAMBIOS' }}"
          - "Reinicio necesario: {{ 'SÍ ⚠️' if reboot_required.stat.exists else 'NO ✓' }}"
          - "================================"
