---
- name: Analyze inteligente AppArmor
  hosts: all
  become: yes

  vars:
    working_dir: /tmp/apparmor_tuning

  tasks:

  - name: 🔍 Validar si hay datos
    stat:
      path: "{{ working_dir }}/runc_raw.log"
    register: log_file

  - name: 🧠 Determinar ejecución
    set_fact:
      apparmor_active: "{{ log_file.stat.exists and log_file.stat.size > 0 }}"

  - name: 📊 Estado
    debug:
      msg: "{{ inventory_hostname }} → {{ 'ANALIZAR ✅' if apparmor_active else 'OMITIDO 🚫' }}"

  - name: 🔍 Extraer paths
    shell: |
      cat {{ working_dir }}/runc_raw.log | \
      grep 'name=' | \
      awk -F 'name=' '{print $2}' | \
      awk '{print $1}' | tr -d '"' | \
      sort | uniq > {{ working_dir }}/runc_paths.txt
    when: apparmor_active
