---
- name: Rollback inteligente AppArmor
  hosts: all
  become: yes

  vars:
    profile: /etc/apparmor.d/usr.bin.runc

  tasks:

  - name: 🔍 Buscar backup
    shell: ls -t {{ profile }}.bak_* | head -1
    register: backup
    failed_when: false

  - name: 🧠 Validar rollback
    set_fact:
      rollback: "{{ backup.stdout != '' }}"

  - name: 📊 Estado
    debug:
      msg: "{{ inventory_hostname }} → {{ 'ROLLBACK ✅' if rollback else 'SIN BACKUP 🚫' }}"

  - name: 🔄 Restaurar
    command: cp {{ backup.stdout }} {{ profile }}
    when: rollback

  - name: 🔄 Recargar
    command: apparmor_parser -r {{ profile }}
    when: rollback

  - name: 🟡 Complain
    command: aa-complain usr.bin.runc
    when: rollback
