---
- name: Apply inteligente AppArmor
  hosts: all
  become: yes

  vars:
    working_dir: /tmp/apparmor_tuning
    profile: /etc/apparmor.d/usr.bin.runc

  tasks:

  - name: 🔍 Verificar state.json
    stat:
      path: "{{ working_dir }}/state.json"
    register: state_stat

  - name: 📥 Leer estado
    slurp:
      src: "{{ working_dir }}/state.json"
    register: state_file
    when: state_stat.stat.exists

  - name: 🧠 Parsear estado
    set_fact:
      state: "{{ state_file.content | b64decode | from_json }}"
    when: state_stat.stat.exists

  - name: 🧠 Default
    set_fact:
      state:
        active: false
    when: not state_stat.stat.exists

  - name: 📊 Estado Apply
    debug:
      msg: "{{ inventory_hostname }} → {{ 'APLICAR ✅' if state.active else 'OMITIDO 🚫' }}"

  - name: 💾 Backup
    copy:
      src: "{{ profile }}"
      dest: "{{ profile }}.bak_{{ ansible_date_time.iso8601 }}"
      remote_src: yes
    when: state.active
    ignore_errors: yes

  - name: 🔧 Insertar reglas
    blockinfile:
      path: "{{ profile }}"
      marker: "# ANSIBLE MANAGED RUNC"
      block: "{{ lookup('file', working_dir + '/rules_optimized.txt') }}"
    when: state.active

  - name: 🔄 Recargar AppArmor
    command: apparmor_parser -r {{ profile }}
    when: state.active

  - name: 🔒 Enforce
    command: aa-enforce usr.bin.runc
    when: state.active
