---
- name: Sincronizar Hora, Zona Horaria e Instalar Cliente NTP
  hosts: servidores_linux # O 'all', si has cambiado el host pattern
  become: true            # Ejecuta todas las tareas con privilegios de root (sudo)
  become_method: sudo
  serial: 3               # Mantiene la consistencia del batch processing

  tasks:
    # -----------------------------------------------
    # FASE 1: PRE-CHECKS Y MANEJO DE LOCKS DE APT
    # -----------------------------------------------
    
    - name: Verificar que el sistema es Debian/Ubuntu
      fail:
        msg: "Este playbook solo funciona en sistemas basados en Debian"
      when: ansible_os_family != "Debian"

    # Tarea añadida para prevenir el fallo del lock (E: Could not open lock file)
    - name: 1. Matar procesos que bloquean APT
      shell: |
        pkill -9 apt || true
        pkill -9 apt-get || true
        pkill -9 dpkg || true
        pkill -9 unattended-upgrade || true
      changed_when: false
      failed_when: false

    # Tarea añadida para limpiar los archivos lock (Permission denied)
    - name: 2. Eliminar locks de APT si existen
      ansible.builtin.file:
        path: "{{ item }}"
        state: absent
      loop:
        - /var/lib/dpkg/lock
        - /var/lib/dpkg/lock-frontend
        - /var/lib/apt/lists/lock
        - /var/cache/apt/archives/lock
      failed_when: false

    # -----------------------------------------------
    # FASE 2: CONFIGURACIÓN DE HORA Y NTP
    # -----------------------------------------------
    
    - name: 3. Establecer la zona horaria a America/Mexico_City 🇲🇽
      community.general.timezone:
        name: America/Mexico_City
      # NOTA: Reemplaza con tu zona horaria deseada.

    - name: 4. Asegurar que el cliente de sincronización horaria 'chrony' este instalado
      ansible.builtin.package:
        name: chrony
        state: present
        
    - name: 5. Habilitar e iniciar el servicio chronyd para la sincronización horaria
      ansible.builtin.service:
        name: chronyd
        state: started
        enabled: yes
      register: ntp_status

    # -----------------------------------------------
    # FASE 3: REPORTE FINAL
    # -----------------------------------------------
    
    - name: Mostrar resumen de configuración de hora
      debug:
        msg:
          - "================================"
          - "Host: {{ inventory_hostname }}"
          - "Zona Horaria Establecida: {{ 'America/Mexico_City' }}"
          - "NTP (chrony) Estado: {{ 'Iniciado/Habilitado (cambio aplicado)' if ntp_status.changed else 'Ya estaba configurado ✓' }}"
          - "================================"
