---
- name: Sincronizar Hora y Establecer Zona Horaria
  hosts: all  # Ajusta este grupo según tu inventario (ej. 'all', 'debian_servers')
  become: true             # Necesario para realizar cambios a nivel de sistema
  become_method: sudo
  serial: 3                # Mantiene la consistencia con tu otro playbook

  tasks:
    # -----------------------------------------------
    # PRE-CHECKS (Mantenido para consistencia)
    # -----------------------------------------------
    - name: Verificar que el sistema es Debian/Ubuntu
      fail:
        msg: "Este playbook solo funciona en sistemas basados en Debian"
      when: ansible_os_family != "Debian"

    - name: Verificar privilegios de root
      command: whoami
      register: current_user
      changed_when: false

    - name: Mostrar usuario actual
      debug:
        msg: "Ejecutando como: {{ current_user.stdout }}"

    # -----------------------------------------------
    # TAREAS DE CONFIGURACIÓN DE HORA
    # -----------------------------------------------
    
    - name: Establecer la zona horaria a America/Mexico_City
      # Módulo 'timezone' maneja automáticamente los cambios persistentes.
      community.general.timezone:
        name: America/Mexico_City 
      # NOTA: Cambia 'America/Mexico_City' a tu zona horaria.

    - name: Asegurar que el cliente de sincronización horaria 'chrony' este instalado
      # Usamos chrony por ser el cliente NTP más moderno y recomendado.
      ansible.builtin.package:
        name: chrony
        state: present
        
    - name: Habilitar e iniciar el servicio chronyd para la sincronización horaria
      # Esto garantiza que la hora se sincronice inmediatamente y al arrancar el sistema.
      ansible.builtin.service:
        name: chronyd
        state: started
        enabled: yes
      register: ntp_status

    # -----------------------------------------------
    # REPORTE FINAL
    # -----------------------------------------------
    
    - name: Mostrar resumen de configuración de hora
      debug:
        msg:
          - "================================"
          - "Host: {{ inventory_hostname }}"
          - "Zona Horaria Establecida: America/Mexico_City"
          - "NTP (chrony) Estado: {{ 'Iniciado/Habilitado' if ntp_status.changed else 'Ya estaba configurado' }}"
          - "================================"
