---
- hosts: all

  become: true

  tasks:
    - name: APT Package Updater
      apt:
        upgrade: yes
        update_cache: yes
    - name: install docker dependencies
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg-agent
          - software-properties-common
        update_cache: yes
    - name: add docker gpg key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
        keyring: /etc/apt/keyrings/docker.gpg
    - name: add docker repository
      apt_repository:
        filename: docker 
        repo: deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename|lower }} stable
        state: present
    - name: install docker engine
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-scan-plugin
          - docker-compose-plugin
        update_cache: yes
    - name: Remove Presearch Node Container
      docker_container:
        name: presearch-node
        state: absent    
    - name: Remove Presearch Node Updater Container
      docker_container:
        name: presearch-auto-updater
        state: absent        
    - name: Create Presearch Node Updater Container
      docker_container:
        name: presearch-auto-updater
        image: presearch/auto-updater
        command: "--cleanup --interval 900 presearch-auto-updater presearch-node"
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock
    - name: Create Presearch Node Container
      docker_container:
        name: presearch-node
        image: presearch/node
        volumes:
          - presearch-node-storage:/app/node
        env:
          REGISTRATION_CODE: '{{REG_CODE}}'
